import Head from "next/head";
import React, { useContext } from "react";
import { useSelector } from "react-redux";
import { GlobalContext } from "../../pages/_app";
import Body from "../Body";
import Navbar from "../Navbar";

const Home = () => {
  
const {state} = useContext(GlobalContext)



  return (
    <div>
      <Head>
        <title>Old Redux with Next JS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar></Navbar>
        <Body component={state.comp}></Body>
      </main>
    </div>
  );
};

export default Home;
